name: daily-commit

on:
  schedule:
    - cron: '5 6 * * *'   # 每天 06:05 UTC（美中部时间约 0:05 AM）自动运行
  workflow_dispatch:        # 允许手动运行一次测试

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Append timestamp
        run: |
          echo "$(date -u) keepalive" >> keepalive.txt

      - name: Set author (use your verified email)
        run: |
          git config user.name "Yukun He"
          git config user.email "kelvinhe0916@gmail.com"  # ✅ 已验证邮箱，贡献会归你

      - name: Commit & Push
        run: |
          git add keepalive.txt
          git commit -m "chore: daily keepalive" || echo "Nothing to commit"
          git push origin HEAD:main
